version: '3.8'

services:
  nginx:
    container_name: tb-proxy
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  api:
    container_name: tb-server
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: "./server"
    volumes:
      - prisma:/app/prisma
    environment:
      NODE_ENV: production
      PORT : 5000

  client:
    container_name: tb-client
    stdin_open: true
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ./client
    environment:
        NODE_ENV: production
volumes:
  prisma: